### ISSUE TITLE
Exception during cleanup

### ISSUE THREAD

**Issue by tjubutsi** [roy-bongers/certbot-transip-dns-01-validator#1] opened 2018-03-28 10:55 UTC
Getting the following when validating:

Waiting for verification...
Cleaning up challenges
Output from cleanup-hook:
Exception received from JSON Server: Invalid API signature, signature does not match the request. (timestamp: 0.34180800 1522232616)

Hook command "/home/user/certbot-transip-dns-01-validator/cleanup-hook" returned error code 1

**Comment by roy-bongers** [comment] 2018-03-28 21:08
The error appears to be coming from the TransIP API. I'm not sure why. Can you verify that the API is working? You could change the following line it should print your domain names at TransIP.

hooks.php line 22:
```
$domains = Transip_DomainService::getDomainNames();
```
to
```
$domains = Transip_DomainService::getDomainNames();
print_r($domains);
```
In the TansIP Control panel do you see that the _acme-challenge DNS record is created? For which domains do you try to request the certificate? Just "domain.com" and *.domain.com" or something else? Could you add the exact certbot command you are using? I'm just trying to figure out what might cause the problem.

**Comment by tjubutsi** [comment] 2018-03-28 21:17
Yeah, the records are created and the validation succeeds. It's just the removal part that doesn't work. I'll add more tomorrow.

**Comment by tjubutsi** [comment] 2018-03-29 07:24
```
> certbot certonly --manual --preferred-challenges=dns --manual-auth-hook /home/skyweb/certbot-transip-dns-01-validator/auth-hook --manual-cleanup-hook /home/skyweb/certbot-transip-dns-01-validator/cleanup-hook -d *.skyweb.nu -d skyweb.nu --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert not due for renewal, but simulating renewal for dry run
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for skyweb.nu
dns-01 challenge for skyweb.nu

-------------------------------------------------------------------------------
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
-------------------------------------------------------------------------------
(Y)es/(N)o: y
Output from auth-hook:
Array
(
    [0] => skyweb.nu
)
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds

Output from auth-hook:
Array
(
    [0] => skyweb.nu
)
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds
Result not ready, retrying in 30 seconds

Waiting for verification...
Cleaning up challenges
Output from cleanup-hook:
Array
(
    [0] => skyweb.nu
)
Exception received from JSON Server: Invalid API signature, signature does not match the request. (timestamp: 0.70628600 1522308194)

Hook command "/home/skyweb/certbot-transip-dns-01-validator/cleanup-hook" returned error code 1
Output from cleanup-hook:
Array
(
    [0] => skyweb.nu
)
Exception received from JSON Server: Invalid API signature, signature does not match the request. (timestamp: 0.17001300 1522308195)

Hook command "/home/skyweb/certbot-transip-dns-01-validator/cleanup-hook" returned error code 1
An unexpected error occurred:
The server experienced an internal error :: Error finalizing order
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by roy-bongers** [comment] 2018-03-29 20:16
Thank you for the information. I think I know what the problem is. Sadly I can't test it myself right now because I don't have access to a computer at the moment. You could try to change the following in hooks.php, around line 56. I think the error occurs because the array keys are not correctly numbered anymore when removing the _acme-challenge records. I've had problems with this before when serializing data.

Change this:
```
elseif ('cleanup' === $_SERVER['ACME_HOOK']) {
	// remove challange DSN entries.
	$dnsEntries = array_filter($dnsEntries, function($dnsEntry) {
		return false === strpos($dnsEntry->name,'_acme-challenge');
	});
}
```
to:
```
elseif ('cleanup' === $_SERVER['ACME_HOOK']) {
	// remove challange DSN entries.
	$dnsEntries = array_filter($dnsEntries, function($dnsEntry) {
		return false === strpos($dnsEntry->name,'_acme-challenge');
	});
	$dnsEntries = array_values($dnsEntries);
}
```

**Comment by roy-bongers** [comment] 2018-03-29 21:45
Cool, thanks for your help! I just applied the fix to the repository so we can close this issue.

**Closed by roy-bongers** 2018-03-29 21:45 UTC
